### ISSUE TITLE
Cobetura and Java 8

### ISSUE THREAD

**Issue by FriederikeHanssen** [qbicsoftware/parent-poms#28]
Cobetura has trouble with lambda expressions in java 8 (https://github.com/cobertura/cobertura/issues/176). One work around could be to use the jacoco plugin, IF it works with travis.

E.g.:
`   <build>
       <plugins>
           <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>0.8.2</version>
                <executions>
                    <execution>
                        <id>jacoco-initialize</id>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>jacoco-report</id>
                        <phase>site</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
         </plugins>
     </build>
`
The report is then added to the site package and can be displayed with target/site/index.html
 `   <reporting>
         ...
         
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <reportSets>
                    <reportSet>
                        <reports>
                            
                            <report>report</report>
                        </reports>
                    </reportSet>
                </reportSets>
            </plugin>
            ...
        </reporting>
 `

**Comment by KochTobi** [comment]
According to [cobertura/cobertura#176](https://github.com/cobertura/cobertura/issues/176#issuecomment-114766252) this has been solved now by updating the cobertura version. Can anyone confirm this?

**Comment by christopher-mohr** [comment]
We're still having issues with Cobertura and as far as I can see there hasn't been a release since the fix has been merged.

**Comment by christopher-mohr** [comment]
We decided to remove Cobertura and go with Jacoco. Solved by 39a4fce4324979f7de966d74f228aedb637ea2b0.
